// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: sfu/sfu.proto

package sfupb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sent from Signalling -> SFU
type SignalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomName string `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Types that are assignable to Payload:
	//	*SignalRequest_Offer
	//	*SignalRequest_IceCandidate
	Payload isSignalRequest_Payload `protobuf_oneof:"payload"`
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sfu_sfu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sfu_sfu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_sfu_sfu_proto_rawDescGZIP(), []int{0}
}

func (x *SignalRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *SignalRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (m *SignalRequest) GetPayload() isSignalRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *SignalRequest) GetOffer() *WebRTCOffer {
	if x, ok := x.GetPayload().(*SignalRequest_Offer); ok {
		return x.Offer
	}
	return nil
}

func (x *SignalRequest) GetIceCandidate() *WebRTCICECandidate {
	if x, ok := x.GetPayload().(*SignalRequest_IceCandidate); ok {
		return x.IceCandidate
	}
	return nil
}

type isSignalRequest_Payload interface {
	isSignalRequest_Payload()
}

type SignalRequest_Offer struct {
	Offer *WebRTCOffer `protobuf:"bytes,3,opt,name=offer,proto3,oneof"`
}

type SignalRequest_IceCandidate struct {
	IceCandidate *WebRTCICECandidate `protobuf:"bytes,4,opt,name=ice_candidate,json=iceCandidate,proto3,oneof"`
}

func (*SignalRequest_Offer) isSignalRequest_Payload() {}

func (*SignalRequest_IceCandidate) isSignalRequest_Payload() {}

// Sent from SFU -> Signalling
type SignalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomName string `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Types that are assignable to Payload:
	//	*SignalResponse_Answer
	//	*SignalResponse_IceCandidate
	Payload isSignalResponse_Payload `protobuf_oneof:"payload"`
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sfu_sfu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sfu_sfu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_sfu_sfu_proto_rawDescGZIP(), []int{1}
}

func (x *SignalResponse) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *SignalResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (m *SignalResponse) GetPayload() isSignalResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *SignalResponse) GetAnswer() *WebRTCAnswer {
	if x, ok := x.GetPayload().(*SignalResponse_Answer); ok {
		return x.Answer
	}
	return nil
}

func (x *SignalResponse) GetIceCandidate() *WebRTCICECandidate {
	if x, ok := x.GetPayload().(*SignalResponse_IceCandidate); ok {
		return x.IceCandidate
	}
	return nil
}

type isSignalResponse_Payload interface {
	isSignalResponse_Payload()
}

type SignalResponse_Answer struct {
	Answer *WebRTCAnswer `protobuf:"bytes,3,opt,name=answer,proto3,oneof"`
}

type SignalResponse_IceCandidate struct {
	IceCandidate *WebRTCICECandidate `protobuf:"bytes,4,opt,name=ice_candidate,json=iceCandidate,proto3,oneof"`
}

func (*SignalResponse_Answer) isSignalResponse_Payload() {}

func (*SignalResponse_IceCandidate) isSignalResponse_Payload() {}

type WebRTCOffer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sdp string `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
}

func (x *WebRTCOffer) Reset() {
	*x = WebRTCOffer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sfu_sfu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebRTCOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRTCOffer) ProtoMessage() {}

func (x *WebRTCOffer) ProtoReflect() protoreflect.Message {
	mi := &file_sfu_sfu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRTCOffer.ProtoReflect.Descriptor instead.
func (*WebRTCOffer) Descriptor() ([]byte, []int) {
	return file_sfu_sfu_proto_rawDescGZIP(), []int{2}
}

func (x *WebRTCOffer) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

type WebRTCAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sdp string `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
}

func (x *WebRTCAnswer) Reset() {
	*x = WebRTCAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sfu_sfu_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebRTCAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRTCAnswer) ProtoMessage() {}

func (x *WebRTCAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_sfu_sfu_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRTCAnswer.ProtoReflect.Descriptor instead.
func (*WebRTCAnswer) Descriptor() ([]byte, []int) {
	return file_sfu_sfu_proto_rawDescGZIP(), []int{3}
}

func (x *WebRTCAnswer) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

type WebRTCICECandidate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Candidate     string `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMid        string `protobuf:"bytes,2,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMlineIndex int32  `protobuf:"varint,3,opt,name=sdp_mline_index,json=sdpMlineIndex,proto3" json:"sdp_mline_index,omitempty"`
}

func (x *WebRTCICECandidate) Reset() {
	*x = WebRTCICECandidate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sfu_sfu_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebRTCICECandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRTCICECandidate) ProtoMessage() {}

func (x *WebRTCICECandidate) ProtoReflect() protoreflect.Message {
	mi := &file_sfu_sfu_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRTCICECandidate.ProtoReflect.Descriptor instead.
func (*WebRTCICECandidate) Descriptor() ([]byte, []int) {
	return file_sfu_sfu_proto_rawDescGZIP(), []int{4}
}

func (x *WebRTCICECandidate) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *WebRTCICECandidate) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *WebRTCICECandidate) GetSdpMlineIndex() int32 {
	if x != nil {
		return x.SdpMlineIndex
	}
	return 0
}

var File_sfu_sfu_proto protoreflect.FileDescriptor

var file_sfu_sfu_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x66, 0x75, 0x2f, 0x73, 0x66, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x73, 0x66, 0x75, 0x22, 0xba, 0x01, 0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x05,
	0x6f, 0x66, 0x66, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x66,
	0x75, 0x2e, 0x57, 0x65, 0x62, 0x52, 0x54, 0x43, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x0d, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x61,
	0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x73, 0x66, 0x75, 0x2e, 0x57, 0x65, 0x62, 0x52, 0x54, 0x43, 0x49, 0x43, 0x45, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x69, 0x63, 0x65, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x22, 0xbe, 0x01, 0x0a, 0x0e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x06, 0x61, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x66, 0x75,
	0x2e, 0x57, 0x65, 0x62, 0x52, 0x54, 0x43, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x0d, 0x69, 0x63, 0x65, 0x5f, 0x63,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x73, 0x66, 0x75, 0x2e, 0x57, 0x65, 0x62, 0x52, 0x54, 0x43, 0x49, 0x43, 0x45, 0x43, 0x61,
	0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x69, 0x63, 0x65, 0x43, 0x61,
	0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0x1f, 0x0a, 0x0b, 0x57, 0x65, 0x62, 0x52, 0x54, 0x43, 0x4f, 0x66, 0x66, 0x65,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x64, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x73, 0x64, 0x70, 0x22, 0x20, 0x0a, 0x0c, 0x57, 0x65, 0x62, 0x52, 0x54, 0x43, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x64, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x73, 0x64, 0x70, 0x22, 0x73, 0x0a, 0x12, 0x57, 0x65, 0x62, 0x52, 0x54, 0x43, 0x49,
	0x43, 0x45, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x64, 0x70,
	0x5f, 0x6d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x64, 0x70, 0x4d,
	0x69, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x64, 0x70, 0x5f, 0x6d, 0x6c, 0x69, 0x6e, 0x65, 0x5f,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x73, 0x64, 0x70,
	0x4d, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x32, 0x43, 0x0a, 0x0a, 0x53, 0x46,
	0x55, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x6c, 0x12, 0x12, 0x2e, 0x73, 0x66, 0x75, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x73, 0x66, 0x75, 0x2e, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x61,
	0x75, 0x68, 0x69, 0x64, 0x2d, 0x55, 0x41, 0x50, 0x2f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2d,
	0x63, 0x68, 0x61, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x66, 0x75, 0x3b, 0x73,
	0x66, 0x75, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sfu_sfu_proto_rawDescOnce sync.Once
	file_sfu_sfu_proto_rawDescData = file_sfu_sfu_proto_rawDesc
)

func file_sfu_sfu_proto_rawDescGZIP() []byte {
	file_sfu_sfu_proto_rawDescOnce.Do(func() {
		file_sfu_sfu_proto_rawDescData = protoimpl.X.CompressGZIP(file_sfu_sfu_proto_rawDescData)
	})
	return file_sfu_sfu_proto_rawDescData
}

var file_sfu_sfu_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sfu_sfu_proto_goTypes = []interface{}{
	(*SignalRequest)(nil),      // 0: sfu.SignalRequest
	(*SignalResponse)(nil),     // 1: sfu.SignalResponse
	(*WebRTCOffer)(nil),        // 2: sfu.WebRTCOffer
	(*WebRTCAnswer)(nil),       // 3: sfu.WebRTCAnswer
	(*WebRTCICECandidate)(nil), // 4: sfu.WebRTCICECandidate
}
var file_sfu_sfu_proto_depIdxs = []int32{
	2, // 0: sfu.SignalRequest.offer:type_name -> sfu.WebRTCOffer
	4, // 1: sfu.SignalRequest.ice_candidate:type_name -> sfu.WebRTCICECandidate
	3, // 2: sfu.SignalResponse.answer:type_name -> sfu.WebRTCAnswer
	4, // 3: sfu.SignalResponse.ice_candidate:type_name -> sfu.WebRTCICECandidate
	0, // 4: sfu.SFUService.Signal:input_type -> sfu.SignalRequest
	1, // 5: sfu.SFUService.Signal:output_type -> sfu.SignalResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sfu_sfu_proto_init() }
func file_sfu_sfu_proto_init() {
	if File_sfu_sfu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sfu_sfu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sfu_sfu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sfu_sfu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebRTCOffer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sfu_sfu_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebRTCAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sfu_sfu_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebRTCICECandidate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sfu_sfu_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SignalRequest_Offer)(nil),
		(*SignalRequest_IceCandidate)(nil),
	}
	file_sfu_sfu_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*SignalResponse_Answer)(nil),
		(*SignalResponse_IceCandidate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sfu_sfu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sfu_sfu_proto_goTypes,
		DependencyIndexes: file_sfu_sfu_proto_depIdxs,
		MessageInfos:      file_sfu_sfu_proto_msgTypes,
	}.Build()
	File_sfu_sfu_proto = out.File
	file_sfu_sfu_proto_rawDesc = nil
	file_sfu_sfu_proto_goTypes = nil
	file_sfu_sfu_proto_depIdxs = nil
}
