// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sfupb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SFUServiceClient is the client API for SFUService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SFUServiceClient interface {
	Signal(ctx context.Context, opts ...grpc.CallOption) (SFUService_SignalClient, error)
}

type sFUServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSFUServiceClient(cc grpc.ClientConnInterface) SFUServiceClient {
	return &sFUServiceClient{cc}
}

func (c *sFUServiceClient) Signal(ctx context.Context, opts ...grpc.CallOption) (SFUService_SignalClient, error) {
	stream, err := c.cc.NewStream(ctx, &SFUService_ServiceDesc.Streams[0], "/sfu.SFUService/Signal", opts...)
	if err != nil {
		return nil, err
	}
	x := &sFUServiceSignalClient{stream}
	return x, nil
}

type SFUService_SignalClient interface {
	Send(*SignalRequest) error
	Recv() (*SignalResponse, error)
	grpc.ClientStream
}

type sFUServiceSignalClient struct {
	grpc.ClientStream
}

func (x *sFUServiceSignalClient) Send(m *SignalRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sFUServiceSignalClient) Recv() (*SignalResponse, error) {
	m := new(SignalResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SFUServiceServer is the server API for SFUService service.
// All implementations must embed UnimplementedSFUServiceServer
// for forward compatibility
type SFUServiceServer interface {
	Signal(SFUService_SignalServer) error
	mustEmbedUnimplementedSFUServiceServer()
}

// UnimplementedSFUServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSFUServiceServer struct {
}

func (UnimplementedSFUServiceServer) Signal(SFUService_SignalServer) error {
	return status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedSFUServiceServer) mustEmbedUnimplementedSFUServiceServer() {}

// UnsafeSFUServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SFUServiceServer will
// result in compilation errors.
type UnsafeSFUServiceServer interface {
	mustEmbedUnimplementedSFUServiceServer()
}

func RegisterSFUServiceServer(s grpc.ServiceRegistrar, srv SFUServiceServer) {
	s.RegisterService(&SFUService_ServiceDesc, srv)
}

func _SFUService_Signal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SFUServiceServer).Signal(&sFUServiceSignalServer{stream})
}

type SFUService_SignalServer interface {
	Send(*SignalResponse) error
	Recv() (*SignalRequest, error)
	grpc.ServerStream
}

type sFUServiceSignalServer struct {
	grpc.ServerStream
}

func (x *sFUServiceSignalServer) Send(m *SignalResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sFUServiceSignalServer) Recv() (*SignalRequest, error) {
	m := new(SignalRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SFUService_ServiceDesc is the grpc.ServiceDesc for SFUService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SFUService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sfu.SFUService",
	HandlerType: (*SFUServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Signal",
			Handler:       _SFUService_Signal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sfu/sfu.proto",
}
